"""empty message

Revision ID: 1cda64d89922
Revises: None
Create Date: 2014-06-09 09:37:05.374445

"""

# revision identifiers, used by Alembic.
revision = '1cda64d89922'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    ### end Alembic commands ###
