"""empty message

Revision ID: 1e16e16ce7ce
Revises: 3335b6166bf6
Create Date: 2014-05-21 12:50:05.604570

"""

# revision identifiers, used by Alembic.
revision = '1e16e16ce7ce'
down_revision = '3335b6166bf6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('result_all', sa.String(length=4000), nullable=True))
    op.add_column('results', sa.Column('result_no_stop_words', sa.String(length=4000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'result_no_stop_words')
    op.drop_column('results', 'result_all')
    ### end Alembic commands ###
