"""empty message

Revision ID: 30f4e0bb8bc2
Revises: None
Create Date: 2014-05-22 18:50:07.801980

"""

# revision identifiers, used by Alembic.
revision = '30f4e0bb8bc2'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_job', sa.String(length=1000), nullable=True),
    sa.Column('second_job', sa.String(length=1000), nullable=True),
    sa.Column('third_job', sa.String(length=1000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('results')
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=1000), nullable=True))
    op.drop_column('users', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'email')
    op.drop_column('users', 'created')
    op.create_table('results',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('result_all', mysql.VARCHAR(length=4000), nullable=True),
    sa.Column('result_no_stop_words', mysql.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('jobs')
    ### end Alembic commands ###
