"""empty message

Revision ID: 3335b6166bf6
Revises: None
Create Date: 2014-05-21 12:46:26.736096

"""

# revision identifiers, used by Alembic.
revision = '3335b6166bf6'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lc_super_users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lc_super_users',
    sa.Column('id', mysql.INTEGER(display_width=7), autoincrement=False, nullable=True),
    sa.Column('community_id', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=2), autoincrement=False, nullable=True),
    sa.Column('auth_id', mysql.INTEGER(display_width=9), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=18), nullable=True),
    sa.Column('is_admin', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('posts_count', mysql.INTEGER(display_width=2), autoincrement=False, nullable=True),
    sa.Column('replies_count', mysql.INTEGER(display_width=3), autoincrement=False, nullable=True),
    sa.Column('thanks_sent_count', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('thanks_received_count', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('up_votes_count', mysql.INTEGER(display_width=6), autoincrement=False, nullable=True),
    sa.Column('down_votes_count', mysql.INTEGER(display_width=5), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('legacy_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avatar_file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avatar_content_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avatar_file_size', mysql.INTEGER(display_width=6), autoincrement=False, nullable=True),
    sa.Column('avatar_updated_at', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('notify_on_thanks_received', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('answers_count', mysql.INTEGER(display_width=5), autoincrement=False, nullable=True),
    sa.Column('discussion_replies_count', mysql.INTEGER(display_width=4), autoincrement=False, nullable=True),
    sa.Column('notifications_read_at', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_login_at', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('last_user_agent', mysql.VARCHAR(length=212), nullable=True),
    sa.Column('last_referer', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('last_remote_ip', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('has_viewed', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('has_searched', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('notifications_count', mysql.INTEGER(display_width=3), autoincrement=False, nullable=True),
    sa.Column('notify_on_new_question_asked', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('questions_count', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('discussions_count', mysql.INTEGER(display_width=3), autoincrement=False, nullable=True),
    sa.Column('up_votes_week_count', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('notify_on_new_question_on_topic', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('notify_on_new_reply_to_followed_posts', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('notify_on_new_discussion_started', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('announcements_last_viewed_at', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('comments_count', mysql.INTEGER(display_width=4), autoincrement=False, nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('results')
    ### end Alembic commands ###
