"""empty message

Revision ID: 51b13372e6ad
Revises: 1e16e16ce7ce
Create Date: 2014-05-21 12:58:32.412655

"""

# revision identifiers, used by Alembic.
revision = '51b13372e6ad'
down_revision = '1e16e16ce7ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
