"""empty message

Revision ID: c10ff50af14
Revises: b1b88940c5b
Create Date: 2014-05-21 23:09:22.203757

"""

# revision identifiers, used by Alembic.
revision = 'c10ff50af14'
down_revision = 'b1b88940c5b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_job', sa.String(length=1000), nullable=True),
    sa.Column('second_job', sa.String(length=1000), nullable=True),
    sa.Column('third_job', sa.String(length=1000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    ### end Alembic commands ###
